my_list = [9, 8, 7, 6, 5, 4, 5, 7, 8, 1, 3]
print("Elements in the list are:", my_list)
print("Counting the no of times 5 is repeated in the list:", my_list.count(5))
print("Element in the list at index 5:", my_list.index(5))
print(my_list.extend([10, 11, 12]))
print("Updated list:", my_list)
my_list.insert(0, 1)
print("Adding 1 at zero index in the list:", my_list)
my_list.remove(10)
print("List after removing:", my_list)
my_list.reverse()
print("Reversed list:", my_list)
my_list.sort()
print("List after sorting:", my_list)
my_list.pop()
print("List after popping an element:", my_list)
print("Multiplying the list:", my_list*2)